{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.repo.name }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - "{{ .Values.domain }}"
      secretName: tls-secret
  {{- end }}
  defaultBackend:
    service:
      name: {{ .Values.repo.name }}
      port:
        number: {{ .Values.service.port }}
  rules:
  - host: "{{ .Values.domain }}"
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.repo.name }}
            port:
              number: {{ .Values.service.port }}
        {{- if .Values.ingress.path }}
        path: /{{ .Values.ingress.path }}
        pathType: Prefix
        {{- end }}
{{- end }}
